# Write your code here!
def game_hash
hash = {:home => {:team_name =>"Brooklyn Nets",:colors => ["Black","White"],
:players => [
  {:player_name => "Alan Anderson",
  :number => 0, 
  :shoe => 16, 
  :points => 22,
  :rebounds => 12,
:assists => 12,
:steals => 3, 
:blocks => 1, 
:slam_dunks => 1},
{:player_name => "Reggie Evans",
:number => 30, 
:shoe => 14, 
:points => 12,
:rebounds => 12,
:assists => 12,
:steals => 12, 
:blocks => 12, 
:slam_dunks => 7},
{:player_name => "Reggie Evans",
:number => 30, 
:shoe => 14, 
:points => 12,
:rebounds => 12,
:assists => 12,
:steals => 12, 
:blocks => 12, 
:slam_dunks => 7},
], 
:away => {:team_name => "nba",:colors => ["red","yell"],:players => [:player_name => 1,:number => 1, :shoe => 2, :points => 3, :rebounds => 3,
:assists => 3,:steals => 3, :steals => 3, :blocks => 4, :slam_dunks => 4]}}

end 